[package]
name = "main"
version = "0.1.0"
authors = ["Shieber <QMH_XB_FLTMY@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core"}
